# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://json.schemastore.org/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "00:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "deps-bun"
      - "automerge"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "00:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "deps-docker"
      - "automerge"
    open-pull-requests-limit: 5
